import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'
import { useState } from "react";
// import GenderSelector from "./gender";

export default function Home() {
  const [content, setContent] = useState([]);
  const show = (x) => { setContent(content => [...content, x]); };

  async function generate(args) {
    try {
      const response = await fetch("/api/generate", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(args),
      });

      const data = await response.json();
      if (response.status !== 200) {
        throw data.error || new Error(`Request failed with status ${response.status}`);
      }
      console.log(data.result);
      return data.result.split(/[\n,]/);
    } catch(error) {
      // Consider implementing your own error handling logic here
      console.error(error);
      alert(error.message);
      return [];
    }
  }

  async function activity() {
    const activities = await generate({ q: 'activity' });
    show(<div>What activity are you shopping for shoes for?</div>);
    show(<div><ul> { activities.map((item, index) => (<li key={index}>{item}</li>)) } </ul></div>);
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
	<div className="text-4xl">Let's ...</div>
	<button className="bg-black rounded-xl text-white font-medium px-4 py-2 sm:mt-10 mt-8 hover:bg-black/70"
	onClick={activity}>buy shoes!</button>
	{content}
      </main>
    </>
  )
}
