import Carousel from "./carousel";
import Head from 'next/head'
import Image from 'next/image'
// import styles from '@/styles/Home.module.css'
import { getPhotos } from '../lib/unsplash';
import { useState, useEffect } from 'react';

function Homes() {
  // return (<Carousel queries={["hiking", "sailing", "museum", "glass blowing", "biking", "playing board games"]} />);
  // return (<Carousel queries={["hiking shoes", "sandals", "ballet flats", "sneakers", "oxfords", "clogs"]} />);
  return (<Carousel queries={["dog", "cat", "bird", "boa", "elephant", "hippo"]} />);
  // return ( <Carousel queries={["Nike Air Max", "Adidas Ultra Boost", "Reebok CrossFit Nano"]} />);
  // return ( <Carousel queries={["Nike Air Max", "Adidas Ultra Boost", "Reebok CrossFit Nano"], ["Running", "Walking", "Jogging"]} />);
}


export default function Home() {
  const [content, setContent] = useState([]);
  const show = (x) => { setContent(content => [...content, x]); };
  const capitalize = (s) => { return s[0].toUpperCase() + s.slice(1); };

  async function generate(args) {
    try {
      const response = await fetch("/api/generate", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(args),
      });

      const data = await response.json();
      if (response.status !== 200) {
        throw data.error || new Error(`Request failed with status ${response.status}`);
      }
      console.log(data.result);
      return data.result.split(/[\n,]/).
        filter(x => x).
	map(x => capitalize(x.replace(/^ /,'').replace(/\.$/,'')));
    } catch(error) {
      // Consider implementing your own error handling logic here
      console.error(error);
      alert(error.message);
      return [];
    }
  }

  async function activity() {
    const activities = await generate({ q: 'activity' });
    show(<div>What kind of shoe are you looking for?</div>);
    show(<div><ul> { activities.map((item, index) => (<li key={item}>{item}</li>)) } </ul></div>);
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
	<div className="text-4xl">Let's ...</div>
	<button className="bg-black rounded-xl text-white font-medium px-4 py-2 sm:mt-10 mt-8 hover:bg-black/70" onClick={activity}>buy shoes!</button>
	{content}
      </main>
    </>
  )
  // main className={styles.main}
}
